### ISSUE TITLE
Compiling on 64bit systems

### ISSUE THREAD

**Issue by m-kuhn** [rave-engine/python3-android#5]
I fail to build here with the following message:

    Traceback (most recent call last):
      File "dev/android/python3-android/src/Python-3.3.5/Lib/runpy.py", line 160, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "dev/android/python3-android/src/Python-3.3.5/Lib/runpy.py", line 73, in _run_code
    exec(code, run_globals)
      File "dev/android/python3-android/src/Python-3.3.5/Lib/lib2to3/pgen2/driver.py", line 22, in <module>
        import logging
      File "dev/android/python3-android/src/Python-3.3.5/Lib/logging/__init__.py", line 26, in <module>
        import sys, os, time, io, traceback, warnings, weakref
    
    ImportError: dev/android/python3-android/src/Python-3.3.5/build/lib.linux-arm-3.3/time.cpython-33m.so: wrong ELF class: ELFCLASS32
    
If hostpython is built with `CCFLAGS=-m32` and `LDFLAGS=-m32` the error turns into the following:

    ImportError: dev/android/python3-android/src/Python-3.3.5/build/lib.linux-arm-3.3/time.cpython-33m.so: cannot open shared object file: No such file or directory

Any idea?

**Comment by Shizmob** [comment]
Now that we've bumped the Python version to 3.4 (a while ago, actually...), some more cross-compilation fixes should be merged in. Could you check if the issue still persists?

**Comment by m-kuhn** [comment]
I don't even remember how I produced this. I'd say, let's close it and if somebody runs into troubles again it can be reopened.
